### PR TITLE
 facepiles: add settings to enable each type independently

### LINKED ISSUE #114: option to disable facepile just for mentions
i like the current logic for mentions that shows them when they're short enough. i'd like to keep that even with facepiles, by exempting either all mentions or short mentions below the threshold. example: https://snarfed.org/podcasts#comment-744582

### PR DESCRIPTION
**Pull request by snarfed**
mentions generally always have meaningful content, and we have good logic for rendering that full content when it's short enough, and excerpts otherwise. so, i'd argue that they should always be rendered, and not facepiled.

cc @dshanske. happy to discuss more if you all disagree!

fixes #114

### CODE REVIEW

**Comment by pfefferle** [comment]
I disagree, because 90% of mentions of my site are way too long and do not distracts readers.

**Comment by snarfed** [comment]
@pfefferle sure, understood. those mentions would still only show up as excerpts or as "This article was mentioned on _xyz_" with this change, though, not with their full text. do you still disagree even with that?

if so, how about an option to let people choose whether to facepile mentions?

**Comment by pfefferle** [comment]
If long posts are displayed as "This article was mentioned on xyz" it is even worse :)

I think we should add a filter/settings for that, so that you could choose which types you want to see as facepiles and which not.

But perhaps we should start using the real comment types instead of `semantic_linkbacks_type` to be more flexible.

**Comment by snarfed** [comment]
ok! added settings to enable facepiles for each type separately. screenshot:

screen shot 2017-11-12 at 7 03 49 pm

**Comment by snarfed** [comment]
friendly ping!

**Comment by snarfed** [comment]
thanks!

**Pull request merged**
