### PR TITLE
Change Comment Class Map to allow multiple class names

### PR DESCRIPTION
**Pull request by dshanske**
I went for a lower level approach and rewrote it a different way. This allows for simpler adding of multiple class names and adds the p-like property I was looking for.

Also fixed a typo.

### CODE REVIEW

**Comment by pfefferle** [comment]
`u-repost` is wrong, it has to be `p-repost`

**Comment by pfefferle** [comment]
An alternative to that case is to add a `u-repost-of`, `u-like-of` or ... directly to the "via" link.

**Comment by pfefferle** [comment]
I found an example in the wiki: https://indiewebcamp.com/tag#mark_up_and_post_a_tag_reply

```html
<span class="h-entry">
 Alice tagged 
 <a class="u-tag-of u-in-reply-to" href="http://s.example.com/post47">Some Article</a>
 as <span class="p-category">tag</span>
</span>
```

**Comment by dshanske** [comment]
The u-repost is a mistake. I thought I changed it to p-repost. Will fix that. Is that the only stumbling point?

The u-???-of... I think the example you show is for posting a tag, not displaying an incoming one.

**Comment by pfefferle** [comment]
Will you send an update (depending the `u-repost`) or should I fix it?

**Comment by dshanske** [comment]
Done.

**Comment by pfefferle** [comment]
Thanks a lot :)

**Pull request merged**
