### PR TITLE
PHPCS and Travis Improvements

### PR DESCRIPTION
**Pull request by dshanske**
This adds the PHPCS and Travis parameters I've done PRs for the other Indieweb plugins on. It ensures that we are checking for PHP 5.3 compatibility as well as fixing a few text domain issues, etc.

After this is committed, next are actual fixes.

### CODE REVIEW

**Comment by pfefferle** [comment]
Thanks!

(But please do not mix code re-formattings with changes in one merge request, it makes it really hard to track the "real" changes.)

**Comment by dshanske** [comment]
I separated them by commit. Sorry.

**Comment by pfefferle** [comment]
Ok, then sorry.

**Comment by pfefferle** [comment]
Can you please disable the php 5.3 test, until @aaronpk changed his code? then I can merge and build a new version.

**Comment by dshanske** [comment]
Disabled the PHP 5.3 test and noted the minimum working version is PHP5.4 for the time being. Once this is merged, I'm going to start working on the comment walker improvements discussed.

**Comment by pfefferle** [comment]
Nice, thanks!

**Pull request merged**
