### PR TITLE
Whitelist Function

### PR DESCRIPTION
**Pull request by dshanske**
This one was what I'd been working on next.

### CODE REVIEW

**Comment by dshanske** [comment]
In future, re the initial request...I'm making it a policy of mine to not submit pull requests at 2AM. Clearly I'm not thinking straight at that time of day. I'm going to hold next time and look at what I did in the morning.

**Comment by dshanske** [comment]
Added another function to support #9 .

**Comment by pfefferle** [comment]
I think it is no good idea to add this to the activation hook, because it could take a lot of time on a blog with lots of old pinbacks! I think this have to be implemented as a cron that runs from time to time and fixes a limited number of pingbacks.

**Comment by pfefferle** [comment]
...it also checks all pingbacks from the spam folder and adds them to the pending list.

**Comment by dshanske** [comment]
The spam thing is easily fixable. I can change to only approved Linkbacks.

Also, will look at a Cron function. Never done Wp Cron. Will have to read
the literature.

**Comment by dshanske** [comment]
Going to work on the Cron. Not sure what you think of the rest.

**Comment by dshanske** [comment]
I added a function that activates a cron job in response to a setting. Not sure how to split the function to just run a few at a time. So, it would spawn a new function to go through pingbacks, but can't figure out the best way to split it. 

Do you think I should drop it for now, and ask you to merge in the other whitelist code, or any suggestions?

**Comment by dshanske** [comment]
I think I figured out a way to easily split the queue and process it a few at a time. But I've really cluttered this Pull Request, so I've pasted the idea into a gist below.

https://gist.github.com/dshanske/6dd4a722d94d37d5b0ef

**Comment by pfefferle** [comment]
will merge this by hand, thanks @dshanske :)

**Pull request closed without merging**
