### PR TITLE
Add invite property

### PR DESCRIPTION
**Pull request by dshanske**
This replaces the rsvp-invite property, references in #139

### CODE REVIEW

**Comment by pfefferle** [comment]
please create a new version for the readme, I just released 4.7.3

**Comment by dshanske** [comment]
Done - rewritten to 3.7.4. Sorry. I couldn't sleep and have been writing PRs.

**Comment by pfefferle** [comment]
Thanks a lot fo the small and clear pull requests

**Comment by dshanske** [comment]
I've been practicing.

**Comment by pfefferle** [comment]
it makes it so much easier to review ;)

thanks for the tests btw.

**Pull request merged**
