### PR TITLE
Fix All But One Tests

### PR DESCRIPTION
**Pull request by dshanske**
I'm not sure why the last test is failing, but I adjusted the other failing one.

### CODE REVIEW

**Comment by pfefferle** [comment]
This does not really help https://travis-ci.org/pfefferle/wordpress-semantic-linkbacks

**Comment by dshanske** [comment]
It fixed everything but one in my version

**Comment by pfefferle** [comment]
Is there something missing in your last pull request?

**Comment by miklb** [comment]
The [log of the build.] Sheds a little more light.

```
1) MicroformatsTest::test_interpreter with data set #1 ('adactio-com')
Failed asserting that an array has the subset Array &0 (
    'comment_author' => 'Jeremy Keith'
    'comment_author_url' => 'http://example.com/webmention/target/placeholder'
    'comment_meta' => Array &1 (
        'semantic_linkbacks_type' => 'mention'
    )
).
/home/travis/build/pfefferle/wordpress-semantic-linkbacks/tests/test-microformats.php:19
```

Unless you've already seen this, in which case, apologies.

**Comment by dshanske** [comment]
I have, just can't figure out why.

**Comment by kraftbj** [comment]
From what I can see, there is no `comment_author` or `comment_author_url` being returned in the array from the parser. I don't know why, but that's the delta so far.

**Comment by kraftbj** [comment]
I added this to the test to get a file to manually inspect:
```ob_start();
		var_dump($comment['comment_author']); // can remove key for the entire output
		$output = ob_get_contents();
		ob_end_clean();
		file_put_contents( '/srv/www/wordpress-develop/src/wp-content/plugins/wordpress-semantic-linkbacks/tmp/' . $file_name, $output);```

**Comment by pfefferle** [comment]
thanks for debugging!

**Pull request merged**
