### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by dshanske**
This builds on the avatar changes made in Webmentions so this plugin will respect the avatar comment types filter. 

It also adds a second domain check against the canonical URL.

It sets up a flag that is passed in $commentdata if the mention is proxied. Proxied in this case means the source URL and the canonical URL are not on the same site. This would be, for example, brid.gy or a similar site. In another PR, Linkbacks_Handler will optionally do something with that information. I just wanted to make sure that it didn't happen in the MF2 code, as the plugin supports an alternate handler. 

This adds a local avatar because when there isn't an avatar, the code is still funneling the result through gravatar even though it knows there is no image. Also registered it as a default in case someone wants it as one.

Added ability to edit type and avatar on the backend.

### CODE REVIEW

**Comment by dshanske** [comment]
Forgot to run the unit tests. Will recheck.

**Comment by dshanske** [comment]
@pfefferle Curious as to your opinion on this.

**Comment by pfefferle** [comment]
I think the CC license (except CC0) is not GPL compatible.

**Comment by dshanske** [comment]
What about the rest of it?

**Comment by dshanske** [comment]
https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses

**Comment by pfefferle** [comment]
GPL v3... WordPress is v2

**Comment by pfefferle** [comment]
I will have a look at the rest later today... thanks for your work

**Comment by dshanske** [comment]
I am sure we can find a compatible generic icon then...

**Comment by pfefferle** [comment]
Sure, I am not against an avatar in general... only want to be sure to have a compatible license...

**Comment by pfefferle** [comment]
Who has discussed that? Only the font files are compatible (`SIL OFL`)... the SVG files are also `CC BY 4.0` so they seem to be not compatible https://fontawesome.com/license

**Comment by dshanske** [comment]
I thought Fontawesome came up during the Indieweb plugin license discussion

**Comment by dshanske** [comment]
But how do we proceed?

**Comment by pfefferle** [comment]
I deleted my comment, fontawesome is compatible, sorry for the confusion... 😔

**Pull request merged**
