### PR TITLE
Change settings page

### PR DESCRIPTION
**Pull request by dshanske**
This moves the settings under Webmentions if that page is set. Depends on a PR in Webmentions.

https://github.com/pfefferle/wordpress-webmention/pull/180

### CODE REVIEW

**Comment by pfefferle** [comment]
Can you try to use these hooks? https://github.com/pfefferle/wordpress-webmention/pull/180

**Comment by dshanske** [comment]
Will give it a shot.

**Comment by dshanske** [comment]
@pfefferle Completely redid this. Fixed the fact register settings was never called also simplified the code immensely.

**Comment by dshanske** [comment]
@pfefferle I think merging this one would make a 3.8 release ready?

**Comment by pfefferle** [comment]
Sure... what do you think about removing the semantic-linkbacks references and show the settings as webmention settings? Is this misleading?

**Pull request merged**
