### PR TITLE
facepile single-emoji reactions aka reacji

### LINKED ISSUE #60: Reacji
https://indieweb.org/reacji#How_to

Bridgy is now displaying Facebook Reactions. Since they are coded as in-reply-to, the plugin displays them as a reply, which means comment form. I'd rather have them remain as webmention types, and allow them to be grouped together.

### PR DESCRIPTION
**Pull request by snarfed**
fixes #60

screenshot:

image

### CODE REVIEW

**Comment by pfefferle** [comment]
Hmm, I am not sure if I love or hate it... could be really noisy if a lot of people reply with different emojis...

Perhaps we should map them to the types we support, like "like" or that we think about a different UI!?!

What do you think?

**Comment by snarfed** [comment]
sure! i can try to put them all inline, which should reduce the vertical space.

even without that, this seems strictly smaller and less noisy than now, with a separate comment for each reaction, right?

in practice, most emoji reactions are from Facebook via Bridgy, which limits to just six. most of my posts with them only have one, ❤️. only a few have more. i think it'd be hard to find any indieweb post anywhere in the wild with more than three or so.

**Comment by pfefferle** [comment]
Have you seen https://wptavern.com/new-feature-plugin-for-wordpress-adds-emoji-reactions-to-posts

**Comment by armingrewe** [comment]
With all these emojis I'm always concerned about compatibility. Someone recently proudly announced on Twitter that the Saltire was now available on their iPhone. All I could see on my Android phone was a black flag.....

**Comment by dshanske** [comment]
I have to agree on mapping if mappable

**Comment by snarfed** [comment]
> Have you seen https://wptavern.com/new-feature-plugin-for-wordpress-adds-emoji-reactions-to-posts

cool! i can't find an example of how they're rendered, though. looks like the author isn't yet using it on his site, https://pento.net/ , and i don't see any screenshots on https://wordpress.org/plugins/react/ or https://make.wordpress.org/core/2016/03/07/reactions/ .

> With all these emojis I'm always concerned about compatibility.

sure! fortunately, this addition is orthogonal. emoji characters are already being rendered right now, without this feature, and they'll be rendered the same way with it.

**Comment by snarfed** [comment]
here's a more compact rendering with all reactions on the same line:

image

**Comment by snarfed** [comment]
by "mapping," are you all proposing showing them inside the likes section, with the emoji composited on top of the avatar, or something similar? like e.g. https://seblog.nl/2017/02/20/4/day-36-reacji ?

image

i'm actually all for that...but it's probably beyond my own personal web dev skills.

in the meantime, i think this is a good intermediate step forward, even if we agree we want to go further eventually.

**Comment by snarfed** [comment]
more examples: https://webmention.herokuapp.com/ 's rendering, e.g. on http://www.kevinmarks.com/twitternazifilter.html :

image

tantek's RSVPs, e.g. http://tantek.com/2017/305/e1/homebrew-website-club :

image

**Comment by alohastone** [comment]
I like this a lot! If you ask me, one could just call it "reactions", and group everything (except comments and replys) altogether. Like so:

hallo aloha weblog 2017-11-13 01-19-56

**Comment by snarfed** [comment]
@alohastone agreed...but which emojis would you use for non-emoji responses? 🔁 may work for repost, but what about likes? probably not 👍 and ❤️, since people regularly use both of them as explicit emoji reactions with distinct meanings.

**Comment by pfefferle** [comment]
I would love a combination of both... keeping the facepiles as is and adding a new section reactions with all reactjis with the avatar and the overlapping emoji.

**Comment by snarfed** [comment]
@pfefferle agreed! done. screenshot:

image

**Comment by pfefferle** [comment]
what about a new comment type reactji, so we can identify the comments on the insert part and not while rendering?

**Comment by snarfed** [comment]
> what about a new comment type reactji, so we can identify the comments on the insert part and not while rendering?

i definitely considered that! i'd prefer that too if we were doing this at the beginning. right now though, there are lots of reacji already accepted and stored, so i wanted a solution that handled them too, not just new ones.

**Comment by pfefferle** [comment]
Thanks for all your work btw!

**Comment by snarfed** [comment]
avatar cache is exciting! it's also arguably less important to backfill, since the difference isn't (immediately) user visible like this is.

if you do want to handle reactions at insert time instead of render time, ok. this seems like a good intermediate step toward it though. i've resolved conflicts, so it's ready to merge if you want!

**Comment by snarfed** [comment]
this is running on my live site now. example: https://snarfed.org/2017-10-31_25851#comments

**Comment by snarfed** [comment]
thank you! 🎉 

i'll go resolve the conflicts in  #125 now.

**Pull request merged**
