### PR TITLE
Add Settings to Disable Facepile Code

### PR DESCRIPTION
**Pull request by dshanske**
With this final setting, I think this can be committed.

### CODE REVIEW

**Comment by pfefferle** [comment]
nice! thanks!

**Comment by dshanske** [comment]
Any chance of a stable release?

**Comment by pfefferle** [comment]
you missed to commit the template file

**Comment by dshanske** [comment]
Which?

**Comment by pfefferle** [comment]
The settings

**Comment by pfefferle** [comment]
`load_template( plugin_dir_path( __FILE__ ) . 'templates/semantic-linkbacks-discussion-settings.php' );`

**Comment by dshanske** [comment]
Ooops. Will fix when I get home

**Pull request merged**
