### PR TITLE
Templates

### PR DESCRIPTION
**Pull request by dshanske**
This is basic support for facepile templates for consideration.

### CODE REVIEW

**Comment by pfefferle** [comment]
Looks Good so far, but I World like to simplify the template... There is a lot of redundancy...

**Comment by dshanske** [comment]
You mean switching it back to a foreach?

**Comment by pfefferle** [comment]
I am not sure...

Do you have an idea how to to use a template per item? kind of `linkbacks-like.php`? The problem is that we have to work with globals or functions because there is no possibility to pass params to templates...

**Comment by dshanske** [comment]
I did something like that in Post Kinds using output buffering

**Comment by dshanske** [comment]
https://github.com/dshanske/indieweb-post-kinds/blob/master/includes/class-kind-view.php#L33 - Basically I used this function like get_template_part to allow not only for the display to be filtered, but templated.

**Comment by pfefferle** [comment]
I like the template part, to be able to overwrite it with the theme...

BTW. looks nice so far https://notiz.blog/2015/12/07/10-jahre-notizblog/

**Pull request merged**
