### PR TITLE
limit facepiles to just the first 8 by default, with link to show all 

### LINKED ISSUE #113: truncate large facepiles, show count and ellipsis
large facepiles can look a bit unweildy. silos handle them by showing a count and just the first few faces, with an option to click and see the full list. with that, you could even consider showing them on top of the replies, instead of below now where many readers will miss them.

### PR DESCRIPTION
**Pull request by snarfed**
fixes #113. i'm open to alternatives for most of the design decisions here!

screenshots, on sempress, before:

image

and after:

image

### CODE REVIEW

**Comment by pfefferle** [comment]
I like it, but I would prefer some settings for that, like the number of facepiles and enable/disable the limiting

**Comment by pfefferle** [comment]
why have you closed it? I think we can extend your request with some settings!

**Comment by snarfed** [comment]
oops, sorry, didn't mean to! accidentally opened this PR from master (bad habit of mine), and i guess force pushing new upstream changes accidentally closed it. reopening!

**Comment by snarfed** [comment]
(i'm adding the settings now)

**Comment by snarfed** [comment]
done! screenshot:

image

**Comment by pfefferle** [comment]
😘

**Pull request merged**
