### PR TITLE
fix facepile fold ellipses other than like

### LINKED ISSUE #125: Expanding beyond 8 photos in facepiles only works for likes
I'm finding that after updating to v3.6.0, when clicking on the ellipses for any of the sections for likes, reposts, or mentions the only section that is expanded is the likes section regardless of which set of ellipses is clicked. It doesn't seem to be possible to expand the reposts or mentions sections (and possibly others like bookmarks, though I've not tested this particular case specifically).

Example: http://boffosocko.com/2017/07/11/the-facebook-algorithm-mom-problem/

### PR DESCRIPTION
**Pull request by snarfed**
fixes #125

### CODE REVIEW

**Comment by snarfed** [comment]
friendly ping!

**Comment by pfefferle** [comment]
Thanks, but thinking about your change for some time, I think it is a bit hacky (surrounding parts of li-elements with spans).

**Comment by snarfed** [comment]
ok! this PR is just a bug fix for a bug in the original merged code, though. it doesn't change any of the markup.

if you want different markup, ok, but let's maybe consider merging this to fix the bug, and then change the markup separately?

**Comment by snarfed** [comment]
friendly ping! i'm totally ok with changing the markup here if you don't like it, but maybe in a different PR? this really is just a bug fix, for a noticeable bug that's already in master.

**Comment by snarfed** [comment]
looks like the fix here got folded into #124, so the resolve resulted in an empty PR, so github closed it. ok!

**Pull request closed without merging**
