### PR TITLE
Some Improvements to Duplicate Strings and Splitting avatar Code

### PR DESCRIPTION
**Pull request by dshanske**

### CODE REVIEW

**Comment by dshanske** [comment]
I need to fix the tests, but @pfefferle does this satisfy the attempt to remove the extra strings?

**Comment by pfefferle** [comment]
LGTM! I like the encapulation of the avatar feature!

**Comment by pfefferle** [comment]
One thing: Can you change the avatar filename to `includes/class-linkbacks-avatar-handler.php` to be consistent?

**Comment by dshanske** [comment]
Will do when I fix the test I broke. More I want to do in future, but I want to get this released first.

**Comment by dshanske** [comment]
@pfefferle I think this is ready to go. I really want to look at the templating code for refactoring at some point. @snarfed put the code that checks if this is a reacji into the Comment Walker, and calls it from outside of there in the comment template. I think it might be better off if that code was elsewhere, possibly setting reacji as a type.

**Comment by dshanske** [comment]
@pfefferle Ready for a new release then, you think?

**Comment by pfefferle** [comment]
Sure!

**Pull request merged**
