### PR TITLE
Fixes and Updates

### PR DESCRIPTION
**Pull request by dshanske**
* Update Emoji Detector and restore 5.3 Compatibility and Testing
* Add dependencies for PHPCS and Codesniffer Standards to Composer Development Dependencies
* Fix a Noted Yoda Condition
* Add a filter to change citation text. Discovered that existing filter would not work as it it used the entire comment text as its variable, not just the citation. 
* Replaced instances of get_comment_meta( 'semantic_linkbacks_type' ) with the get_type function previously introduced.

### CODE REVIEW

**Comment by pfefferle** [comment]
„All checks have failed“

**Comment by dshanske** [comment]
Can you have a look at it more closely? For some reason, the tests you implemented are failing only on the PHP 5.3 install, which has to use an older version of PHPUnit, for example. That isn't something I introduced exactly, it's reenabling PHP5.3 support. 

Secondly, the Codeclimate issue is that html5_comment is too long...over 25 lines. Do you really want me to split that?

**Comment by pfefferle** [comment]
> Can you have a look at it more closely? For some reason, the tests you implemented are failing only on the PHP 5.3 install, which has to use an older version of PHPUnit, for example. That isn't something I introduced exactly, it's reenabling PHP5.3 support.

@snarfed introduced the tests and they seem to fail in different situations, for example on emoji tests. Do we really need to be PHP 5.3 compatible?

> Secondly, the Codeclimate issue is that html5_comment is too long...over 25 lines. Do you really want me to split that?

no ;)

**Comment by pfefferle** [comment]
@dshanske it seems that you missed to commit the `regexp.json` from the emoji detector lib

**Comment by dshanske** [comment]
I will try it and try troubleshooting further. Do I really need to refactor html5_comment due length?

**Comment by pfefferle** [comment]
> Do I really need to refactor html5_comment due length?

No, I already marked it as `wontfix`

**Comment by dshanske** [comment]
I'm still stumped here. It is only failing on PHP5.3.

**Comment by pfefferle** [comment]
at least there is only one last error instead of the three before... are you sure the whole emoji stuff is working under PHP 5.3?

**Comment by dshanske** [comment]
No. That's the idea of testing. I suppose that 5.4 might be the new minimum

**Comment by pfefferle** [comment]
I think we should release a new version soon because of some bug fixes, will you give it some more tries, or should we change compatibility? I am ok with 5.4!

**Comment by dshanske** [comment]
So am I. If I can't figure it out today, I will revert to 5.4 so you can merge the request

**Comment by armingrewe** [comment]
Just out of curiosity, why do you want to support 5.3? To my knowledge 5.6 is the only 5 version still receiving (some) support from the PHP crew. At my hoster I believe you have to pay extra to use any PHP5 version (certainly for anything below 5.6, not entirely sure about 5.6), they actively push you towards 7.

**Comment by dshanske** [comment]
@armingrewe Because people are still on it. The decision we made for the Indieweb plugins was to support the lowest version of PHP that supported what functionality we needed. We've had people unable to use the plugins because they were on 5.3 or 5.4. So, for example, anything with the PHP-MF2 parser needs minimum 5.3. 

If you look at Wordpress Stats overall, https://wordpress.org/about/stats/ - 9.8% of people are still on 5.3. So, by making this decision, we just cut off 10% of possible users. But adding functionality beats compatibility in my mind. If we can't reconcile the two, we have to compromise somewhere.

**Comment by dshanske** [comment]
@pfefferle I bumped the version to 3.7.0, added the changelog, and redeclared 5.4 or greater compatibility. If someone installs it on PHP5.3 it should still work, less the emoji stuff, so that should be fine.

**Comment by dshanske** [comment]
@armingrewe To give another example, we asked the PHP-MF2 repo and the Emoji detector library to remove short array notation(which didn't come in until 5.4) so the library could be used. But switching from declaring arrays as [] to array() didn't hurt anything.

**Comment by armingrewe** [comment]
@dshanske thanks for the explanation, really appreciated. Makes sense now.

**Comment by pfefferle** [comment]
thanks, I have to clean up the changelog a bit, because I removed some stuff ;)

**Pull request merged**
