### PR TITLE
render full mention content if it's short enough (default to <= 300 chars)

### PR DESCRIPTION
**Pull request by snarfed**

### CODE REVIEW

**Comment by snarfed** [comment]
here are some examples of this: https://snarfed.org/2016-06-11_decentralized-web-summit#comment-2599187

some are ugly because their sites' mf2 is missing or incomplete, e.g. @kevinmarks's :P

**Comment by snarfed** [comment]
thanks!

**Comment by kevinmarks** [comment]
Hm, that's my known site, so should have good mf2

**Comment by pfefferle** [comment]
@kevinmarks I think @snarfed had kind of a similar problem a while ago... The test is starting with a tab or several whitespaces and @snarfed is using a plugin which interprets it as a code block...

**Comment by snarfed** [comment]
true! i was actually thinking about the extra stuff, though, not the formatting. it looks like http://known.kevinmarks.com/2016/decentralized-web-summit-snarfedorg is a like, but it doesn't have `u-like[-of]` ([here's the parsed mf2](https://kylewm.com/services/mf2?url=http://known.kevinmarks.com/2016/decentralized-web-summit-snarfedorg)), and it doesn't have `e-content` or `p-summary` either, so the whole `h-entry` gets dragged in. maybe it's an old version of known?

anyway. definitely not a big deal!

**Pull request merged**
