### PR TITLE
Filter to Support Linkback Moderation

### PR DESCRIPTION
**Pull request by dshanske**
Cleaned up and ready for consideration.

### CODE REVIEW

**Comment by pfefferle** [comment]
Shouldn't that be part of the WebMention plugin?

**Comment by dshanske** [comment]
That wouldn't cover Pingbacks and Trackbacks.

**Comment by dshanske** [comment]
In response to discussion, have removed the whitelist in favor of only the filter to support it.

**Comment by dshanske** [comment]
Re the commentdata filter, the reason I wanted the extra filter is the point in the process...after it has already determined if it is a reply/comment, not a mention. That could probably be solved by adding that check to anything I attach to the filter.

**Comment by pfefferle** [comment]
But the type is already determined at this point and it is part of the array `_type`...

**Comment by dshanske** [comment]
Good point. The changing of the comment_type from webmention to ""(comment) is what I was thinking of. But that check could be done based on the _type.

**Comment by pfefferle** [comment]
there is also a filter for that: `semantic_linkbacks_comment_types` let's you define for what types the "webmention" `comment_type` should be removed. If you want to remove it for all, add all types the plugin supports... If you want to remove it for none, remove all types from the array...

**Comment by dshanske** [comment]
Then I can approach it in that way instead.

On Tue, Mar 3, 2015 at 5:07 PM, Matthias Pfefferle <notifications@github.com

**Comment by pfefferle** [comment]
I don't want to argue against you suggestions, I only want to keep the number of filters low, to lower the complexity and to keep the plugin fast...

**Comment by dshanske** [comment]
I understand. I want things to be the best possible as well.

**Pull request closed without merging**
