### PR TITLE
MF2 Improvements - Take Two

### PR DESCRIPTION
**Pull request by dshanske**
This is an attempt to rewrite the previous PR. It takes away some of the extra complexity and tries to simplify, while accomplishing the same goals.

### CODE REVIEW

**Comment by pfefferle** [comment]
Again the

```
Matthias Pfefferle mentioned this Article on Array.
```

problem and a broken type detection.

**Comment by pfefferle** [comment]
I committed the tests, perhaps they will help.

**Comment by dshanske** [comment]
I tested several sites manually, but I will try against the tests.

**Comment by pfefferle** [comment]
I got 0 errors without the changes and 6 after your changes... but feel also free to recheck/extend my test cases...

**Comment by dshanske** [comment]
I intend to keep working at it until I get it to work to spec.

**Comment by pfefferle** [comment]
The current version is not that bad, but perhaps you have some exotic examples...

**Comment by dshanske** [comment]
That is why I am not giving up. I think the changes I want to make sets up for a lot of future improvements.

**Comment by dshanske** [comment]
Somehow on rebasing, accidentally lost the commit. Going to have to fix.

**Comment by dshanske** [comment]
I will not open a new PR until it passes the tests.

**Pull request closed without merging**
